// Generated by tools/sync-release-metadata.js from package.json.
'use strict';

(function exposeFoxBearBuildInfo(global) {
  const info = Object.freeze({
    productVersion: '1.5.22',
    appVersion: 'Pro v1.5.22',
    buildId: 'header-preview-routing-polish',
    assetVersion: '1.5.22-header-preview-routing-polish',
    cacheName: 'foxbear-shell-v1.5.22-header-preview-routing-polish',
    bootRevision: 'boot-sri-v1522',
    updateSafetyRevision: 'update-safety-v1522',
    serviceWorkerRevision: 'sw-v1522'
  });
  global.FoxBearBuildInfo = info;
})(typeof window !== 'undefined' ? window : globalThis);
