// Generated by tools/sync-release-metadata.js from package.json.
'use strict';

(function exposeFoxBearBuildInfo(global) {
  const info = Object.freeze({
    productVersion: '1.7.1',
    appVersion: 'Pro v1.7.1',
    buildId: 'reference-match-2-phase1',
    assetVersion: '1.7.1-reference-match-2-phase1',
    cacheName: 'foxbear-shell-v1.7.1-reference-match-2-phase1',
    bootRevision: 'boot-sri-v171',
    updateSafetyRevision: 'update-safety-v171',
    serviceWorkerRevision: 'sw-v171',
    lazyAssets: Object.freeze({
      adminIncidentMonitor: Object.freeze({
        scriptPath: 'src/ui/admin-incident-monitor-view.js',
        stylePath: 'assets/css/components/admin-incident-monitor.css',
        scriptIntegrity: 'sha384-EkM5I9u62hysHtiNHU8VJCDj3xlbUgOEyZUaj8C7hfdOxAbRrfvV5+wnV4E+q/sp',
        styleIntegrity: 'sha384-DziwLpc6frFhgGJNfQtBi0I4Ahsc/ENn0LhrJ0+tPSlzvweut81oy+pKLir/B76t'
      })
    })
  });
  global.FoxBearBuildInfo = info;
})(typeof window !== 'undefined' ? window : globalThis);
