// FoxBear AI Mastering Studio Pro v1.6.97 - extracted runtime state module
'use strict';

const state = {
    tracks: [],
    uiMode: '',
    selectedId: null,
    selectedIds: new Set(),
    busy: false,
    programmatic: false,
    lastToastTimer: null,
    featureFlags: {
        trimSilence: true,
        albumMatch: false,
        truePeakGuard: true,
        aiHumanize: true,
        vocalProtect: true,
        smartGuard: true,
        lowEndAnchor: true,
        melodyPreserve: true,
        transientRefine: true,
        vocalFocusPlus: true,
        adaptiveAir: true,
        translationGuard: true,
        openMixGuard: true,
        referenceMatch: true,
        phaseSafe: true,
        earFatigueGuard: true
    },
    albumProfile: null,
    referenceProfile: null,
    outputFormat: 'wav24',
    masterGoal: 'natural',
    masterStyle: 'streaming',
    masterStrength: 'balanced',
    targetLufs: -14,
    adaptiveTargetLufs: true,
    referenceMatchStrength: 0.62,
    ceilingDb: -1.0,
    qualityMode: 'balanced',
    platformPreset: 'custom',
    performanceMode: 'auto',
    pitchEngine: 'auto',
    abLevelMatch: false,
    abDifferenceListen: false,
    abLoopMode: false,
    autoCacheClean: true,
    autoHighlightAB: false,
    smartPerformanceGuard: true,
    engineSafetyMeter: true,
    cacheReady: false,
    autoRemasterTimers: new Map(),
    selectPopup: null,
    selectPopupKeyBound: false,
    expandedDetailIds: new Set(),
    collapsedDetailIds: new Set(),
    popupScrollY: 0,
    popupScrollbarCompensation: 0,
    activeDownloadUrls: new Set(),
    realtimePreview: null,
    previewRenderTimer: null,
    bottomPreviewLayoutObserverInstalled: false,
    bottomPreviewLayoutRaf: 0,
    bottomPreviewResizeObserver: null,
    bottomPreviewIntegrityRaf: 0,
    bottomPreviewRepairCount: 0,
    bottomPreviewLastRepairReason: '',
    bottomPreviewLastIntegrityAt: 0,
    bottomPreviewMode: 'original',
    bottomPreviewTrackId: null,
    masterPreviewRenderingTrackId: null,
    masterPreviewRenderingJobId: '',
    bottomPreviewAutoplayTrackId: null,
    previewTranslationMode: 'studio',
    bottomPreviewTransport: null,
    dockController: null,
    dockRemoteDelegationInstalled: false,
    featureDialogClosingUntil: 0,
    featureTooltipTimer: null,
    managedModalControllerInstalled: false,
    mobileNative: null,
    modalController: null,
    adminTapLastAt: 0,
    adminTapCount: 0,
    adminStatsRemoteError: '',
    adminIncidentsRemoteError: '',
    adminMonitorView: 'visits',
    adminAccessChecking: false,
    adminUnlockBusy: false,
    adminLogoutBusy: false,
    adminSessionExpiresAt: '',
    firebaseAdminChecked: false,
    firebaseIsAdmin: false,
    firebaseAdminRole: '',
    firebaseAdminEmail: '',
    firebaseAdminDisplayName: '',
    firebaseAdminProvider: '',
    firebaseReady: false,
    firebaseUserId: '',
    firebaseError: '',
    firebaseVisitLogged: false,
    firebaseRemoteNotice: '',
    firebaseNoticeShown: false,
    lastAdminVisitEvent: null
};

const el = {};
