const fs = require('fs');
const html = fs.readFileSync('index.html', 'utf8');
const app = fs.readFileSync('src/app.js', 'utf8');
const css = fs.readFileSync('assets/css/studio.css', 'utf8');
const dockCss = fs.readFileSync('assets/css/dock.css', 'utf8');
const dockWaveformCss = fs.readFileSync('assets/css/dock-waveform.css', 'utf8');
const compareCss = fs.readFileSync('assets/css/waveform-compare.css', 'utf8');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
function must(cond, msg) { if (!cond) { console.error(msg); process.exit(1); } }
must(html.includes('data-build="1.4.26"'), 'index build should be v1.4.26');
must(app.includes("const APP_VERSION = 'Pro v1.4.26'"), 'app version should be v1.4.0');
must(app.includes("const SHARED_DSP_PROFILE_VERSION = 'v1.4.0-dock-modal-state-machine'"), 'DSP slug should be v1.4.0');
must(pkg.version === '1.4.26', 'package version should be 1.4.26');
must(app.includes('function getAdaptiveDockWaveformBinCount'), 'adaptive dock waveform bin count helper missing');
must(app.includes('function updateWaveformProgressBars'), 'waveform progress bar class helper missing');
must(app.includes("bar.classList.toggle('is-played'"), 'played waveform segment class update missing');
must(app.includes('dock-waveform-polished'), 'polished dock waveform class missing');
must(css.includes('v1.4.0 Dock / Modal State Machine Refactor'), 'v1.4.0 waveform CSS section missing');
must(css.includes('align-items: center !important'), 'mirror waveform center alignment missing');
must(css.includes('is-played'), 'played segment contrast CSS missing');
must(css.includes('width: 9px !important') || dockCss.includes('width: 9px !important') || dockWaveformCss.includes('width: 9px !important') || compareCss.includes('width: 6px !important'), 'glow capsule playhead CSS missing');
must(css.includes('white-space: nowrap !important'), 'nowrap label CSS missing');
must(dockCss.includes('v1.4.0 Dock / Modal State Machine Refactor'), 'dock CSS v1.4.0 section missing');
console.log('PASS icon refresh and button view close repair smoke');
