#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const compareSource = fs.readFileSync('src/ui/waveform-compare-view.js','utf8');
const mobileSource = fs.readFileSync('src/ui/mobile-native-view.js','utf8');
const appSource = fs.readFileSync('src/app.js','utf8');
const runtimeHealthSource = fs.readFileSync('src/boot/runtime-health.js','utf8');
const pkg = JSON.parse(fs.readFileSync('package.json','utf8'));
assert.strictEqual(pkg.version,'1.6.110');
assert(fs.existsSync('docs/V1.5.77_RUNTIME_RESOURCE_LIFECYCLE_RECOVERY.md'));
assert(!fs.existsSync('src/ui/spectrum-visualizer.js'),'retired spectrum resource lifecycle module must stay deleted');
assert(compareSource.includes('controls._foxbearDispose = () =>'));
assert(compareSource.includes('wrap._foxbearDispose = () =>'));
assert(appSource.includes("unregisterPlaybackLinkedAudio(audio, 'bottom-preview-clear')"));
assert(appSource.includes("clearPreviewDialogBody('waveform-compare-open')"));
assert(!runtimeHealthSource.includes('FoxBearSpectrumVisualizer'));
assert(mobileSource.includes("globalObject.visualViewport?.addEventListener?.('resize', positionPanel"));
assert(mobileSource.includes('panel._foxbearDisposePositioning = () =>'));
console.log('PASS v1.5.77 runtime resource lifecycle with spectrum UI retired');
