'use strict';
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const root = path.resolve(__dirname, '..');
const read = p => fs.readFileSync(path.join(root, p), 'utf8');
const assert = (c, m) => { if (!c) throw new Error(m); };
const index = read('index.html');
const app = read('src/app.js');
const build = read('src/config/build-info.js');
const loader = read('src/ui/admin-incident-loader-service.js');
assert(!/admin-incident-monitor-view\.js[^\n]*<\/script>/.test(index), 'admin incident monitor JS must not be eagerly loaded by index.html');
assert(index.includes('assets/css/components/admin-incident-monitor.css'), 'shared admin monitor CSS must stay eager so visit tabs are styled before incident JS loads');
assert(app.includes('ensureAdminIncidentMonitorAssets') && app.includes('FoxBearAdminIncidentLoaderService'), 'admin incident lazy loader delegation missing');
assert(!app.includes('appendLazyStylesheet'), 'shared admin CSS should not be delayed');
assert(loader.includes('options.resolveScriptUrl(options.src)') && loader.includes('script.integrity = String(options.integrity)'), 'lazy admin script must retain Trusted Types and SRI');
assert(app.includes('SERVICE_WORKER_URL, ADMIN_INCIDENT_MONITOR_SCRIPT_URL])'), 'lazy admin script must be on exact trusted script allowlist');
const sri = bytes => `sha384-${crypto.createHash('sha384').update(bytes).digest('base64')}`;
assert(build.includes(`scriptIntegrity: '${sri(fs.readFileSync(path.join(root, 'src/ui/admin-incident-monitor-view.js')))}'`), 'admin JS SRI mismatch');
const hygienePolicy = read('tools/source-hygiene-policy.js');
const deletes = new Set(read('DELETE_PATHS.txt').split(/\r?\n/));
['APPLY_SPECTRUM_DELETE_NO_GIT.cmd','APPLY_SPECTRUM_DELETE_NO_GIT.sh','README_FIRST.txt'].forEach(p => { assert(deletes.has(p), `temporary helper cleanup missing: ${p}`); assert(hygienePolicy.includes(`'${p}'`), `temporary helper must be source-hygiene forbidden: ${p}`); });
console.log('PASS v1.6.101 admin incident JS lazy-load, SRI/Trusted Types, and temporary helper cleanup');
